name: CI/CD to AWS EC2 Instance with Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_SECRET }}

      # 4️⃣ Build & push backend image
      - name: Build and push backend image
        uses: docker/build-push-action@v6
        with:
          context: ./springbootbackend
          file: ./springbootbackend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/dockeraws-backend:latest

      # 5️⃣ Build & push frontend image
      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          context: ./reactfrontend
          file: ./reactfrontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USER }}/dockeraws-frontend:latest

      # 6️⃣ Save EC2 private key
      - name: Save EC2 private key
        run: |
          echo "${{ secrets.AWS_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      # 7️⃣ Deploy to AWS EC2
      - name: Deploy to AWS EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@${{ secrets.AWS_IP }} << 'EOF'
            cd DOCKER-FULLSTACK-PROJECT || git clone https://github.com/${{ github.repository }}.git
            cd DOCKER-FULLSTACK-PROJECT
            git pull origin main
            sudo docker-compose down
            sudo docker-compose pull
            sudo docker-compose up -d --build
          EOF
